language: node_js
node_js:
  - "stable"
cache: yarn

notification:
  email: false

before-install:
  - cd frontend
install:
  - yarn

script:
  - yarn format
  - yarn test
  - yarn build

deploy:
	on:
		branch: master	  
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS
	secret_access_key: $AWS_SECRET
	bucket: "what-up"
	local_dir: build
