language: node_js
node_js:
  - "stable"
cache: yarn

notification:
  email: false

before-install:
  - cd frontend
install:
  - yarn

script:
  - yarn format
  - yarn test
  - yarn build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  bucket: "what-up"
  skip_cleanup: true
